name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements-dev.txt
            - name: Lint with flake8
              run: flake8 pureshell
            - name: Check formatting with black
              run: black --check pureshell
            - name: Type check with mypy
              run: mypy pureshell
            - name: Run tests with coverage
              run: pytest --cov=pureshell --cov-report=xml
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  slug: zinthose/pureshell
