name: Publish Python Package to PyPI

on:
    release:
        types: [created] # Trigger only when a new release is published

permissions:
    id-token: write # Needed for trusted publishing with PyPI

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/pureshell # Link to the PyPI project
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install build twine

            - name: Build package
              run: python -m build

            - name: Publish package to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              # No `with: password:` is needed here because we are using trusted publishing.
              # Ensure PyPI is configured to trust this repository and workflow for the 'pureshell' package.
